### ISSUE TITLE
2+ Permanent URL  not showing together 

### ISSUE THREAD

**Issue by Samirah89** [djplaner/Card-Interface-Tweak#22]
When creating a link to a permanent url it's fine for the first one but not for the subsequent one. they don't show up in the cards

**Comment by djplaner** [comment]
Thanks for raising the issue.  
I'm assuming that the permanent URL you mention is for the card image?
If that is the case, I believe I've re-created the problem. To do this I copy and pasted the permanent URL for the card image into the item.  To produce the following.

![Screenshot from 2021-02-03 12-38-26](https://user-images.githubusercontent.com/225052/106690108-e4e0fe80-661c-11eb-895e-ff9f4db90f82.png)

Note: how the **Card Image:** URL is an active link?  Is this similar to what you've done?

If so, I'm in the process of fixing the problem.  If not, any further information to help me recreate the problem would be welcome.

**Comment by Samirah89** [comment]
Hi David, 

The permanent URL is for linking to documents to the item that should show in the cards as below:
![image](https://user-images.githubusercontent.com/52098760/106694006-89266d80-663c-11eb-9f07-336cf68a1b20.png)
see how course calendar is linked. so when students click on it, it will take them to the course calendar page,
however in the item we have linked to documents using the permanent link 
![image](https://user-images.githubusercontent.com/52098760/106694095-ba9f3900-663c-11eb-803d-4986546141ba.png)
but both the links are not showing together on the card. if one is there the other doesn't show. This happens for another card as well. 

please let me know if you require anymore information.
Regards
Samirah

**Comment by djplaner** [comment]
Thank you.  That helps identify the use case.  I'll see what I can do to fix the problem ASAP.

In the meantime, if you need an immediate solution/workaround, edit the description so just the text of the URL appears. Rather than the image. As shown below.   

![Screenshot from 2021-02-03 14-04-38](https://user-images.githubusercontent.com/225052/106696621-d4368580-6628-11eb-9940-d6efbe740626.png)

**Comment by Samirah89** [comment]
Hi David,

Thanks for that. 
It'll be great if this could be resolved soon before we go live with our courses. 

Appreciate your help.
Thanks
Samirah

**Comment by djplaner** [comment]
G'day Samirah,

I've just rolled out some changes that I believe fix your issue (and a somewhat related one). At least in my tests.  
Please do let me know if the issue isn't fixed for you.

## Before

![before](https://user-images.githubusercontent.com/225052/106831342-76af4100-66db-11eb-92c7-e48a5c53b077.png)

## After

Note: _Before_  a URL was missing in the first card (*Some permanent URL*) and one in the second (*https://bblearn..*).  New code is handling them correctly.

![after](https://user-images.githubusercontent.com/225052/106831472-b2e2a180-66db-11eb-9a97-955b382f241f.png)

Thanks again for reporting the problem.

David.

**Comment by Samirah89** [comment]
Hi David,

thasnk you so muhc for looking into this.

unfortunatley this hasn't fixed the issue for us. When we link to documents/readings  on the same card only one of them shows instead of both. i tried doing it again:

in the item i created two links (as shown below):
![image](https://user-images.githubusercontent.com/52098760/106972343-8dc26180-67b5-11eb-9c9a-f7dfcf544710.png)
see how two items are linked. However in the cards it shows like this:
![image](https://user-images.githubusercontent.com/52098760/106972385-9f0b6e00-67b5-11eb-8e0c-4f621209e6e3.png)

Is there something that we're overlooking?

Regards
Samirah

**Comment by djplaner** [comment]
That's a pity.  Sorry.  Thank you for letting me know.  This is helpful to me because if you're having this problem, then chances are someone I work with will have similar problems.

I wasn't certain that the issue I replicated and fixed, was exactly the one you are using.  That's the bit that was overlooked.

### Source of the problem

This is all associated with how the Card Interface parses the HTML in the content item for the specific card.  The oversight is that the HTML I'm working with (and fixing) isn't exactly the same as the HTML causing you problems.

The best solution I can think of for this is if you could send me a copy of the HTML for the content item that has the problem.  This will allow me to examine exactly what's going wrong.

I'll explain how below.  Completely understand if you'd prefer not to do this or don't have the time.

### How

The basic process is (details below)
1. Rather than screenshot the content item with the problem, Inspect the element
2. Copy the HTML for the element
3. Send it to me here or [via email](mailto:davidthomjones@gmail.com).

#### Inspect the element

i.e. if you can view the content item with the problem (e.g. the following), rather than take a screenshot use your browser to _inspect_ the element.  Exactly how you do this depends on the browser you are using (some [generic instructions](https://www.lifewire.com/get-inspect-element-tool-for-browser-756549))

Using the image below as an example, it means _right clicking_ on the word **Card Image:** in the item.  This typically opens up another section showing the HTML code for the item.

![problem](https://user-images.githubusercontent.com/225052/106977548-4c768580-67a6-11eb-8f7a-ba665876b7c1.png)

#### Copy the HTML

The following image is what I see when I inspect a content item.  

![Screenshot from 2021-02-05 11-39-55](https://user-images.githubusercontent.com/225052/106977925-f48c4e80-67a6-11eb-95b1-134bcc45088f.png)

You will see something a little different, but you should hopefully be able to see the following HTML.  This is the HTML Blackboard uses for the content for one of its items.  If you can send me the HTML within this item I can fix the problem.

```html
<div class="details">
  <div class="vtbegenerated">
```

To do this, you can hopefully _right click_ on the **div class="details"** item.  This will bring up a menu. One of the options on the menu should be **Copy**.   The **Copy** option might have a couple of different options.  One of which should mention **HTML**.  Perhaps **Outer HTML** or **Inner HTML**.

Please click on **Outer HTML** if it's there.

This will copy just the HTML for this item into your clipboard.  It will look something like the code at the end of this message.

#### Send it to me

With the HTML in your clipboard, please paste it into a response to this message or perhaps to [my email address](mailto:davidthomjones@gmail.com)

```html
<div class="details">
    <div class="vtbegenerated"> 
 <p>
  Testing out some description content.
 </p> 
 <p>
  This should work with multi pargraphs
 </p> 
 <p>
  <strong>Font formatting </strong>
  <em>and other Html</em>
 </p> 
 <p>
  <br>
 </p> 
 <p>
  Card Date: Week 1
 </p> 
 <p>
  Card Date Label: Before
 </p> 
 <p>
  Card Image Size: contain
 </p> 
 <p>
  Card Label:
 </p> 
 <p>
  Card Image Iframe: 
  <iframe src="https://griffitheduau.sharepoint.com/sites/HLSSacademic/_layouts/15/Doc.aspx?sourcedoc={0ceb11f5-0510-40d4-89d5-1caba39e899f}&amp;action=embedview&amp;wdAr=1.7777777777777777" width="350" height="221" frameborder="0"></iframe>
 </p> 
</div>
  </div>
```

**Comment by Samirah89** [comment]
Hi David,

The issue seems to resolved now. the links are working fine and appearing on the cards

Really appreciate  your time and effort. thanks you very much.

Regards
Samirah

**Comment by djplaner** [comment]
Great news Samirah.  

I'm assuming the delay may have been caused by a need to refresh the cached version of the card javascript.

Thanks for letting me know and please feel free to pass along any other problems or suggestions for enhancements.

David.
