### ISSUE TITLE
Assessment Card Dates Not displaying 

### ISSUE THREAD

**Issue by Samirah89** [djplaner/Card-Interface-Tweak#29]
Hi David,

Hope you'r doing fine.

we have an issue where the card date and card label for the assessment cards are not showing. 
![image](https://user-images.githubusercontent.com/52098760/107910502-680c3800-6fbf-11eb-8e78-87d1a85de98e.png)
we put in the tags as written in the instructions but it doesn't appear on the cards:
![image](https://user-images.githubusercontent.com/52098760/107910543-84a87000-6fbf-11eb-9faf-bf36c9bb9c05.png)
could you please have a look or suggest a work around please.

Thanks 
Samirah

**Comment by djplaner** [comment]
G'day Samirah,

I suspect that this problem is solely due to the limitations of the Card Interface and some design choices.  In particular, the way it's been [designed to understand dates](https://djplaner.github.io/Card-Interface-Tweak/customiseACard/#adding-a-date-or-date-range).

In the above, you've used ```Card date: 22 Apr```  the date before the month.  The Card Interface only recognises the reverse order

**Comment by Samirah89** [comment]
Hi David,

Awesome, thanks for clarifying that for us. 
Appreciate your help.


Regards
Samirah
